### PR TITLE
Added more objects in events.content

### PR DESCRIPTION
**Pull request by cb-senthilvel**
Added more objects quotes, unbilled charges in events.content

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @cb-senthilvel, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cb-senthilvel** [comment]
@cmerrick  we already signed cla. Should I sign in CLA for every PR

**Comment by briansloane** [comment]
@cb-senthilvel I've confirmed you already signed the CLA. I'll get you added to our database so the automated flagging doesn't do this in the future.

**Comment by KAllan357** [comment]
I think our forks have diverged. This needs to be rebased on our master or maybe you could just fork ours?

**Comment by luandy64** [comment]
Can we also swap the tabs in `gifts.json` for spaces?

**Comment by luandy64** [comment]
All changes made in this fork/branch have been merged into `singer-io/master`

**Pull request closed without merging**
